# Docker Compose para Notifications Service
version: '3.8'

services:
  notifications-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=buscamiperro_notifications
      - PORT=3006
    depends_on:
      - postgres
    networks:
      - buscamiperro-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buscamiperro_notifications
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - buscamiperro-network

volumes:
  postgres_data:

networks:
  buscamiperro-network:
    driver: bridge