# Docker Compose para Profile Service
version: '3.8'

services:
  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=buscamiperro_profiles
      - PORT=3007
    depends_on:
      - postgres
    networks:
      - buscamiperro-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buscamiperro_profiles
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - buscamiperro-network

volumes:
  postgres_data:

networks:
  buscamiperro-network:
    driver: bridge